server:
  port: 8081
  context-path: /lucene-search/
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mappers/**/*.xml
  type-aliases-package: com.zero.model

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zero_user_web?characterEncoding=UTF-8@&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456

    hikari:
      #一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒以上
      maxLifetime: 1765000
      #连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
      maximumPoolSize: 15
      connection-test-query: SELECT 1 FROM DUAL
      minimum-idle: 1
      pool-name: Primary-Pool
  aop:
    auto: true
    proxy-target-class: true

search:
  lucene:
    path: E://data//server//directory